# Generated by Django 4.2.13 on 2024-07-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_blog_audience_blog_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='topic',
            new_name='blogIdea',
        ),
    ]
